# Generated by Django 6.0.1 on 2026-01-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, help_text='Full LinkedIn URL (https://...)', max_length=255),
        ),
    ]
