# Generated by Django 6.0.1 on 2026-01-13 20:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_profile_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=3, help_text='1-5 scale', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming_skills', to='resume.profile')),
            ],
            options={
                'verbose_name': 'Programozási ismeret',
                'verbose_name_plural': 'Programozási ismeretek',
            },
        ),
    ]
